### ISSUE TITLE
Problem with Fira font from Google on Garfunkel theme

### ISSUE THREAD

**Issue by DamienCasoni** [CFCommunity-net/cfcommunity#9]
It doesn't render on some OS and browsers.
[Even the creator recommend to use](https://github.com/mozilla/Fira) `<link rel="stylesheet" href="//code.cdn.mozilla.net/fonts/fira.css">` instead of the Google API.

Personally, I don't know where to change it in Garfunkel since it's not in the header.php...

**Comment by BoweFrankema** [comment]
Hi Damien, seems like you accidentally created the issue/comment in the wrong repo?

**Comment by DamienCasoni** [comment]
Sorry I'm very new to Github, I don't know what happened.. :/
Feel free to remove it.
